package es.miguelherrero.sunshine.models

data class WeatherModel(val main: Main)

data class ForecastModel(val cod: String,
                         val message: Float,
                         val cnt: Int,
                         val city: City,
                         val list: List<Day>)

data class City(val id: Int,
                val name: String,
                val coord: Coord,
                val country: String)

data class Coord(val lat: Float,
                 val lon: Float)

data class Day(val dt: Int,
               val main: Main,
               val weather: List<Weather>,
               val dt_txt: String)

data class Main(val temp: Float,
                val temp_min: Float,
                val temp_max: Float,
                val pressure: Float,
                val humidity: Int)

data class Weather(val id: Int,
                   val main: String,
                   val description: String,
                   val icon: String)


/*
https://api.openweathermap.org/data/2.5/forecast?id=3117735&appid=
{
   "cod":"200",
   "message":0.0033,
   "cnt":37,
   "list":[
      {
         "dt":1532768400,
         "main":{
            "temp":306.72,
            "temp_min":298.397,
            "temp_max":306.72,
            "pressure":957.1,
            "sea_level":1028.17,
            "grnd_level":957.1,
            "humidity":37,
            "temp_kf":8.32
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.82,
            "deg":254
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-28 09:00:00"
      },
      {
         "dt":1532779200,
         "main":{
            "temp":309.56,
            "temp_min":303.317,
            "temp_max":309.56,
            "pressure":956.35,
            "sea_level":1027.1,
            "grnd_level":956.35,
            "humidity":29,
            "temp_kf":6.24
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.07,
            "deg":248.504
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-28 12:00:00"
      },
      {
         "dt":1532790000,
         "main":{
            "temp":309.92,
            "temp_min":305.753,
            "temp_max":309.92,
            "pressure":955.46,
            "sea_level":1026.02,
            "grnd_level":955.46,
            "humidity":20,
            "temp_kf":4.16
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.32,
            "deg":247.005
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-28 15:00:00"
      },
      {
         "dt":1532800800,
         "main":{
            "temp":307.03,
            "temp_min":304.948,
            "temp_max":307.03,
            "pressure":955.04,
            "sea_level":1025.62,
            "grnd_level":955.04,
            "humidity":20,
            "temp_kf":2.08
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.66,
            "deg":249.503
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-28 18:00:00"
      },
      {
         "dt":1532811600,
         "main":{
            "temp":297.277,
            "temp_min":297.277,
            "temp_max":297.277,
            "pressure":955.89,
            "sea_level":1027.07,
            "grnd_level":955.89,
            "humidity":32,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.16,
            "deg":244
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-28 21:00:00"
      },
      {
         "dt":1532822400,
         "main":{
            "temp":293.538,
            "temp_min":293.538,
            "temp_max":293.538,
            "pressure":956.52,
            "sea_level":1027.93,
            "grnd_level":956.52,
            "humidity":40,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.21,
            "deg":234.503
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-29 00:00:00"
      },
      {
         "dt":1532833200,
         "main":{
            "temp":291.018,
            "temp_min":291.018,
            "temp_max":291.018,
            "pressure":956.4,
            "sea_level":1027.98,
            "grnd_level":956.4,
            "humidity":59,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.86,
            "deg":216.001
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-29 03:00:00"
      },
      {
         "dt":1532844000,
         "main":{
            "temp":290,
            "temp_min":290,
            "temp_max":290,
            "pressure":957.19,
            "sea_level":1028.89,
            "grnd_level":957.19,
            "humidity":66,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.51,
            "deg":211.002
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-29 06:00:00"
      },
      {
         "dt":1532854800,
         "main":{
            "temp":300.234,
            "temp_min":300.234,
            "temp_max":300.234,
            "pressure":957.9,
            "sea_level":1029.17,
            "grnd_level":957.9,
            "humidity":40,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.41,
            "deg":234
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-29 09:00:00"
      },
      {
         "dt":1532865600,
         "main":{
            "temp":304.399,
            "temp_min":304.399,
            "temp_max":304.399,
            "pressure":956.94,
            "sea_level":1027.79,
            "grnd_level":956.94,
            "humidity":31,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":4.26,
            "deg":236.502
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-29 12:00:00"
      },
      {
         "dt":1532876400,
         "main":{
            "temp":306.479,
            "temp_min":306.479,
            "temp_max":306.479,
            "pressure":955.75,
            "sea_level":1026.34,
            "grnd_level":955.75,
            "humidity":23,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":4.92,
            "deg":247.002
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-29 15:00:00"
      },
      {
         "dt":1532887200,
         "main":{
            "temp":304.712,
            "temp_min":304.712,
            "temp_max":304.712,
            "pressure":955.5,
            "sea_level":1026.11,
            "grnd_level":955.5,
            "humidity":17,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":4.76,
            "deg":247.002
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-29 18:00:00"
      },
      {
         "dt":1532898000,
         "main":{
            "temp":297.493,
            "temp_min":297.493,
            "temp_max":297.493,
            "pressure":956.83,
            "sea_level":1027.86,
            "grnd_level":956.83,
            "humidity":22,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":4.42,
            "deg":247.001
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-29 21:00:00"
      },
      {
         "dt":1532908800,
         "main":{
            "temp":293.381,
            "temp_min":293.381,
            "temp_max":293.381,
            "pressure":957.27,
            "sea_level":1028.73,
            "grnd_level":957.27,
            "humidity":36,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.62,
            "deg":232.501
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-30 00:00:00"
      },
      {
         "dt":1532919600,
         "main":{
            "temp":289.832,
            "temp_min":289.832,
            "temp_max":289.832,
            "pressure":957.21,
            "sea_level":1028.87,
            "grnd_level":957.21,
            "humidity":48,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"02n"
            }
         ],
         "clouds":{
            "all":8
         },
         "wind":{
            "speed":2.42,
            "deg":223.5
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-30 03:00:00"
      },
      {
         "dt":1532930400,
         "main":{
            "temp":287.441,
            "temp_min":287.441,
            "temp_max":287.441,
            "pressure":957.45,
            "sea_level":1029.25,
            "grnd_level":957.45,
            "humidity":65,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.11,
            "deg":174
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-30 06:00:00"
      },
      {
         "dt":1532941200,
         "main":{
            "temp":298.281,
            "temp_min":298.281,
            "temp_max":298.281,
            "pressure":958.03,
            "sea_level":1029.19,
            "grnd_level":958.03,
            "humidity":30,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.78,
            "deg":239.502
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-30 09:00:00"
      },
      {
         "dt":1532952000,
         "main":{
            "temp":303.966,
            "temp_min":303.966,
            "temp_max":303.966,
            "pressure":957.1,
            "sea_level":1027.81,
            "grnd_level":957.1,
            "humidity":26,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.12,
            "deg":254.501
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-30 12:00:00"
      },
      {
         "dt":1532962800,
         "main":{
            "temp":306.614,
            "temp_min":306.614,
            "temp_max":306.614,
            "pressure":955.72,
            "sea_level":1026.21,
            "grnd_level":955.72,
            "humidity":21,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.41,
            "deg":252.002
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-30 15:00:00"
      },
      {
         "dt":1532973600,
         "main":{
            "temp":305.507,
            "temp_min":305.507,
            "temp_max":305.507,
            "pressure":955.28,
            "sea_level":1025.73,
            "grnd_level":955.28,
            "humidity":18,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.66,
            "deg":252.001
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-30 18:00:00"
      },
      {
         "dt":1532984400,
         "main":{
            "temp":297.714,
            "temp_min":297.714,
            "temp_max":297.714,
            "pressure":956.18,
            "sea_level":1027.15,
            "grnd_level":956.18,
            "humidity":27,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.77,
            "deg":244.502
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-30 21:00:00"
      },
      {
         "dt":1532995200,
         "main":{
            "temp":293.587,
            "temp_min":293.587,
            "temp_max":293.587,
            "pressure":956.43,
            "sea_level":1027.8,
            "grnd_level":956.43,
            "humidity":38,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.86,
            "deg":240.002
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-31 00:00:00"
      },
      {
         "dt":1533006000,
         "main":{
            "temp":288.627,
            "temp_min":288.627,
            "temp_max":288.627,
            "pressure":956.2,
            "sea_level":1027.65,
            "grnd_level":956.2,
            "humidity":67,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":0.97,
            "deg":233.5
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-31 03:00:00"
      },
      {
         "dt":1533016800,
         "main":{
            "temp":287.495,
            "temp_min":287.495,
            "temp_max":287.495,
            "pressure":956.42,
            "sea_level":1027.91,
            "grnd_level":956.42,
            "humidity":72,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":0.36,
            "deg":213.503
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-31 06:00:00"
      },
      {
         "dt":1533027600,
         "main":{
            "temp":299.634,
            "temp_min":299.634,
            "temp_max":299.634,
            "pressure":956.68,
            "sea_level":1027.65,
            "grnd_level":956.68,
            "humidity":34,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.41,
            "deg":221.003
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-31 09:00:00"
      },
      {
         "dt":1533038400,
         "main":{
            "temp":305.214,
            "temp_min":305.214,
            "temp_max":305.214,
            "pressure":955.61,
            "sea_level":1026.25,
            "grnd_level":955.61,
            "humidity":27,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.05,
            "deg":246.001
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-31 12:00:00"
      },
      {
         "dt":1533049200,
         "main":{
            "temp":307.67,
            "temp_min":307.67,
            "temp_max":307.67,
            "pressure":953.9,
            "sea_level":1024.23,
            "grnd_level":953.9,
            "humidity":20,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.16,
            "deg":241.007
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-31 15:00:00"
      },
      {
         "dt":1533060000,
         "main":{
            "temp":306.569,
            "temp_min":306.569,
            "temp_max":306.569,
            "pressure":953.11,
            "sea_level":1023.47,
            "grnd_level":953.11,
            "humidity":18,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.22,
            "deg":257.001
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-07-31 18:00:00"
      },
      {
         "dt":1533070800,
         "main":{
            "temp":297.213,
            "temp_min":297.213,
            "temp_max":297.213,
            "pressure":953.68,
            "sea_level":1024.63,
            "grnd_level":953.68,
            "humidity":32,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.55,
            "deg":242.501
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-07-31 21:00:00"
      },
      {
         "dt":1533081600,
         "main":{
            "temp":292.91,
            "temp_min":292.91,
            "temp_max":292.91,
            "pressure":953.87,
            "sea_level":1025.02,
            "grnd_level":953.87,
            "humidity":46,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.86,
            "deg":272.507
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-08-01 00:00:00"
      },
      {
         "dt":1533092400,
         "main":{
            "temp":290.137,
            "temp_min":290.137,
            "temp_max":290.137,
            "pressure":953.8,
            "sea_level":1025.18,
            "grnd_level":953.8,
            "humidity":65,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.62,
            "deg":356.5
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-08-01 03:00:00"
      },
      {
         "dt":1533103200,
         "main":{
            "temp":290.464,
            "temp_min":290.464,
            "temp_max":290.464,
            "pressure":954.68,
            "sea_level":1026.23,
            "grnd_level":954.68,
            "humidity":65,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.5,
            "deg":29.5021
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-08-01 06:00:00"
      },
      {
         "dt":1533114000,
         "main":{
            "temp":300.709,
            "temp_min":300.709,
            "temp_max":300.709,
            "pressure":955.47,
            "sea_level":1026.45,
            "grnd_level":955.47,
            "humidity":39,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":3.4,
            "deg":42.5054
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-08-01 09:00:00"
      },
      {
         "dt":1533124800,
         "main":{
            "temp":307.217,
            "temp_min":307.217,
            "temp_max":307.217,
            "pressure":954.73,
            "sea_level":1025.27,
            "grnd_level":954.73,
            "humidity":27,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":2.66,
            "deg":58.5083
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-08-01 12:00:00"
      },
      {
         "dt":1533135600,
         "main":{
            "temp":309.323,
            "temp_min":309.323,
            "temp_max":309.323,
            "pressure":953.66,
            "sea_level":1023.88,
            "grnd_level":953.66,
            "humidity":22,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.67,
            "deg":14.0043
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-08-01 15:00:00"
      },
      {
         "dt":1533146400,
         "main":{
            "temp":308.511,
            "temp_min":308.511,
            "temp_max":308.511,
            "pressure":953.19,
            "sea_level":1023.5,
            "grnd_level":953.19,
            "humidity":19,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01d"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.75,
            "deg":8.00378
         },
         "sys":{
            "pod":"d"
         },
         "dt_txt":"2018-08-01 18:00:00"
      },
      {
         "dt":1533157200,
         "main":{
            "temp":298.247,
            "temp_min":298.247,
            "temp_max":298.247,
            "pressure":954.12,
            "sea_level":1024.93,
            "grnd_level":954.12,
            "humidity":53,
            "temp_kf":0
         },
         "weather":[
            {
               "id":800,
               "main":"Clear",
               "description":"clear sky",
               "icon":"01n"
            }
         ],
         "clouds":{
            "all":0
         },
         "wind":{
            "speed":1.31,
            "deg":7.00659
         },
         "sys":{
            "pod":"n"
         },
         "dt_txt":"2018-08-01 21:00:00"
      }
   ],
   "city":{
      "id":3117735,
      "name":"Madrid",
      "coord":{
         "lat":40.4165,
         "lon":-3.7026
      },
      "country":"ES"
   }
}
 */